/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package employee_management;

import java.awt.Component;
import java.awt.Image;
import java.awt.event.KeyEvent;
import javax.swing.*;
import java.util.*;
import java.io.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import java.util.Vector;
import java.util.regex.*;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author patil
 */
public class AddEmployee extends javax.swing.JFrame {

    public AddEmployee() {
        initComponents();
    }
    
    public String searchFilterate;
    
    public int fetchIndex() {
            for (int index = 0; index < tableEmployees.getColumnCount(); index++) {
                if (tableEmployees.getColumnName(index).equals(searchFilterate)) 
                {
                    return index;
                }
            }
        return -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderGroup = new javax.swing.ButtonGroup();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        javax.swing.JButton btnAdd = new javax.swing.JButton();
        javax.swing.JButton btnClear = new javax.swing.JButton();
        tfName = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        tfPhone = new javax.swing.JTextField();
        tfPosition = new javax.swing.JTextField();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel9 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel10 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel11 = new javax.swing.JLabel();
        javax.swing.JButton btnDelete = new javax.swing.JButton();
        tfAge = new javax.swing.JTextField();
        tfGender = new javax.swing.JTextField();
        tfEmpId = new javax.swing.JTextField();
        tfStartDate = new javax.swing.JTextField();
        tfTeamInfo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnBrowse = new javax.swing.JButton();
        jLabelImage = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        agLabel = new javax.swing.JLabel();
        empIDLabel = new javax.swing.JLabel();
        levelLabel = new javax.swing.JLabel();
        teamLabel = new javax.swing.JLabel();
        teamInfoLabel = new javax.swing.JLabel();
        reviewButton = new javax.swing.JButton();
        tfLevel = new javax.swing.JTextField();
        nameLBL = new javax.swing.JLabel();
        ageLbl = new javax.swing.JLabel();
        empIDLbl = new javax.swing.JLabel();
        dateLbl = new javax.swing.JLabel();
        emailLbl = new javax.swing.JLabel();
        positionLbl = new javax.swing.JLabel();
        itemBox = new javax.swing.JComboBox<>();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        tableEmployees = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add an Employee to the system");
        setMinimumSize(new java.awt.Dimension(1167, 790));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(235, 235, 168));
        jPanel1.setMaximumSize(new java.awt.Dimension(767, 736));
        jPanel1.setPreferredSize(new java.awt.Dimension(767, 736));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee_management/contact-book.png"))); // NOI18N
        jLabel1.setText("Employee Directory");
        jLabel1.setIconTextGap(25);

        jPanel2.setBackground(new java.awt.Color(239, 235, 235));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "New Employee", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 1, 18))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jPanel2.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel3.setText("Email");

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel4.setText("Phone");

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel5.setText("Position Title");

        btnAdd.setBackground(new java.awt.Color(0, 153, 153));
        btnAdd.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee_management/add (3).png"))); // NOI18N
        btnAdd.setText("Add");
        btnAdd.setToolTipText("");
        btnAdd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdd.setIconTextGap(10);
        btnAdd.setMargin(new java.awt.Insets(5, 20, 3, 20));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(0, 153, 153));
        btnClear.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee_management/delete-user (1).png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnClear.setIconTextGap(10);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        tfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameActionPerformed(evt);
            }
        });
        tfName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfNameKeyReleased(evt);
            }
        });

        tfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailActionPerformed(evt);
            }
        });
        tfEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfEmailKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfEmailKeyReleased(evt);
            }
        });

        tfPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPhoneActionPerformed(evt);
            }
        });
        tfPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfPhoneKeyPressed(evt);
            }
        });

        tfPosition.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPositionKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel6.setText("Employee ID");

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel7.setText("Age");

        jLabel8.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel8.setText("Gender");

        jLabel9.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel9.setText("Start Date");

        jLabel10.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel10.setText("Level");

        jLabel11.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel11.setText("Team Info");
        jLabel11.setToolTipText("");

        btnDelete.setBackground(new java.awt.Color(0, 153, 153));
        btnDelete.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee_management/delete-user.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDelete.setIconTextGap(10);
        btnDelete.setInheritsPopupMenu(true);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        tfAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAgeActionPerformed(evt);
            }
        });
        tfAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfAgeKeyReleased(evt);
            }
        });

        tfGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfGenderActionPerformed(evt);
            }
        });
        tfGender.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfGenderKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfGenderKeyReleased(evt);
            }
        });

        tfEmpId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfEmpIdKeyReleased(evt);
            }
        });

        tfStartDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfStartDateActionPerformed(evt);
            }
        });
        tfStartDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfStartDateKeyReleased(evt);
            }
        });

        tfTeamInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTeamInfoActionPerformed(evt);
            }
        });
        tfTeamInfo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfTeamInfoKeyReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee_management/search (1).png"))); // NOI18N
        jLabel12.setText("Search Employee:");
        jLabel12.setIconTextGap(10);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(0, 153, 153));
        btnUpdate.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee_management/edit.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUpdate.setIconTextGap(10);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnBrowse.setBackground(new java.awt.Color(0, 153, 153));
        btnBrowse.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        btnBrowse.setForeground(new java.awt.Color(255, 255, 255));
        btnBrowse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee_management/browsing.png"))); // NOI18N
        btnBrowse.setText("Browse Image");
        btnBrowse.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBrowse.setIconTextGap(10);
        btnBrowse.setMargin(new java.awt.Insets(5, 20, 3, 20));
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        jLabelImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 51, 0), 3));

        nameLabel.setForeground(new java.awt.Color(255, 0, 51));

        emailLabel.setForeground(new java.awt.Color(255, 51, 51));

        ageLabel.setForeground(new java.awt.Color(255, 0, 0));

        jLabel13.setForeground(new java.awt.Color(255, 51, 51));

        agLabel.setForeground(new java.awt.Color(255, 51, 51));

        empIDLabel.setForeground(new java.awt.Color(255, 51, 51));

        levelLabel.setForeground(new java.awt.Color(255, 51, 51));

        teamLabel.setForeground(new java.awt.Color(255, 0, 0));

        teamInfoLabel.setForeground(new java.awt.Color(255, 51, 51));

        reviewButton.setBackground(new java.awt.Color(0, 153, 153));
        reviewButton.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        reviewButton.setForeground(new java.awt.Color(255, 255, 255));
        reviewButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee_management/male.png"))); // NOI18N
        reviewButton.setText("Review");
        reviewButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reviewButton.setIconTextGap(10);
        reviewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reviewButtonActionPerformed(evt);
            }
        });

        tfLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLevelActionPerformed(evt);
            }
        });
        tfLevel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfLevelKeyReleased(evt);
            }
        });

        nameLBL.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        nameLBL.setForeground(new java.awt.Color(204, 0, 0));

        ageLbl.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ageLbl.setForeground(new java.awt.Color(255, 0, 0));

        empIDLbl.setForeground(new java.awt.Color(255, 0, 0));

        dateLbl.setForeground(new java.awt.Color(255, 0, 0));

        emailLbl.setForeground(new java.awt.Color(255, 0, 0));

        positionLbl.setForeground(new java.awt.Color(255, 0, 0));

        itemBox.setBackground(new java.awt.Color(0, 153, 153));
        itemBox.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        itemBox.setForeground(new java.awt.Color(255, 255, 255));
        itemBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Name", "Age", "Gender", "EMail", "Phone", "Employee ID", "Start Date", "Level", "Team Info", "Position Title" }));
        itemBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                itemBoxMouseExited(evt);
            }
        });
        itemBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBoxActionPerformed(evt);
            }
        });
        itemBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                itemBoxKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(133, 133, 133)
                                        .addComponent(dateLbl))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(itemBox, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(levelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(reviewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(427, 427, 427)
                                        .addComponent(positionLbl)
                                        .addGap(209, 209, 209)
                                        .addComponent(btnBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(89, 89, 89))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfName, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                                    .addComponent(tfEmpId)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tfAge, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(46, 46, 46))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(ageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(7, 7, 7)))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(63, 63, 63)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tfGender, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel10)
                                                    .addComponent(tfLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(51, 51, 51)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(emailLbl)
                                                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel11)
                                                    .addComponent(tfTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addComponent(tfStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(empIDLbl))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(63, 63, 63)
                                .addComponent(jLabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teamInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(teamLabel)
                .addGap(194, 194, 194)
                .addComponent(agLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(182, 182, 182)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172)
                .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(emailLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(agLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ageLabel)
                            .addComponent(jLabel13))
                        .addGap(61, 61, 61)
                        .addComponent(empIDLabel)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(teamLabel))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(teamInfoLabel))
                            .addComponent(levelLabel))
                        .addContainerGap(141, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfEmpId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(empIDLbl)
                            .addComponent(dateLbl)
                            .addComponent(positionLbl))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd)
                            .addComponent(btnClear)
                            .addComponent(btnUpdate)
                            .addComponent(btnDelete)
                            .addComponent(reviewButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(itemBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(nameLBL)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailLbl)
                            .addComponent(ageLbl))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBrowse)
                .addGap(109, 109, 109))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAdd, btnClear, btnDelete, btnUpdate, reviewButton});

        tableEmployees.setBackground(new java.awt.Color(239, 235, 235));
        tableEmployees.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tableEmployees.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tableEmployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Age", "Gender", "EMail", "Phone", "Employee ID", "Start Date", "Level", "Team Info", "Position Title", "Image"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableEmployees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableEmployeesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableEmployees);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1143, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(35, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(292, 292, 292)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1098, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1161, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        DefaultTableModel model = (DefaultTableModel) tableEmployees.getModel();
        
        Vector<Vector> tableData = model.getDataVector();        
       
        //Saving the object in a file
        try{
            FileOutputStream file = new FileOutputStream("file.bin");
            ObjectOutputStream output = new ObjectOutputStream(file);
            
            //Method for serialization of Object
            output.writeObject(tableData);
            file.close();
        }catch (Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try{
            FileInputStream file = new FileInputStream("file.bin");
            ObjectInputStream input = new ObjectInputStream(file);
            
            //Method for serialization of Object
            Vector<Vector> tableData = (Vector<Vector>)input.readObject();
            
            input.close();
            file.close();
            
            //Adding data to the table
            DefaultTableModel model = (DefaultTableModel) tableEmployees.getModel();
            for(int i=0; i<tableData.size(); i++){
                Vector row = tableData.get(i);
                model.addRow(new Object[]{row.get(0), row.get(1), row.get(2), row.get(3), row.get(4), row.get(5),row.get(6), row.get(7), row.get(8), row.get(9), row.get(10)});
            }
        }
        catch(EOFException e){
           
        }
        catch (Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    private void tableEmployeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEmployeesMouseClicked
       DefaultTableModel model = (DefaultTableModel) tableEmployees.getModel();
       int index=tableEmployees.getSelectedRow();
       tfName.setText(model.getValueAt(index,0).toString());
       tfAge.setText(model.getValueAt(index,1).toString());
       tfGender.setText(model.getValueAt(index,2).toString());
       tfEmail.setText(model.getValueAt(index,3).toString());
       tfPhone.setText(model.getValueAt(index,4).toString());
       tfEmpId.setText(model.getValueAt(index,5).toString());
       tfStartDate.setText(model.getValueAt(index,6).toString());
       tfLevel.setText(model.getValueAt(index,7).toString());
       tfTeamInfo.setText(model.getValueAt(index,8).toString());
       tfPosition.setText(model.getValueAt(index,9).toString());
       
       ImageIcon ii = new ImageIcon(model.getValueAt(tableEmployees.getSelectedRow(), 10).toString());
       //Resize image to fit jlabel
       Image image = ii.getImage().getScaledInstance(jLabelImage.getWidth(), jLabelImage.getHeight(), Image.SCALE_SMOOTH);
       jLabelImage.setIcon(new ImageIcon(image));
    }//GEN-LAST:event_tableEmployeesMouseClicked

    private void tfLevelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfLevelKeyReleased

    }//GEN-LAST:event_tfLevelKeyReleased

    private void tfLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLevelActionPerformed

    private void reviewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reviewButtonActionPerformed

        ReviewEmployee x = new ReviewEmployee();
        ReviewEmployee.jLabel24.setText(AddEmployee.tfName.getText());
        ReviewEmployee.jLabel25.setText(AddEmployee.tfAge.getText());
        ReviewEmployee.jLabel26.setText(AddEmployee.tfGender.getText());
        ReviewEmployee.jLabel27.setText(AddEmployee.tfEmail.getText());
        ReviewEmployee.jLabel28.setText(AddEmployee.tfPhone.getText());
        ReviewEmployee.jLabel29.setText(AddEmployee.tfEmpId.getText());
        ReviewEmployee.jLabel30.setText(AddEmployee.tfStartDate.getText());
        ReviewEmployee.jLabel31.setText(AddEmployee.tfLevel.getText());
        ReviewEmployee.jLabel32.setText(AddEmployee.tfTeamInfo.getText());
        ReviewEmployee.jLabel33.setText(AddEmployee.tfPosition.getText());
        ReviewEmployee.jLabel34.setIcon(AddEmployee.jLabelImage.getIcon());
        x.setVisible(true);
    }//GEN-LAST:event_reviewButtonActionPerformed

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        //Setting default browser location
        JFileChooser browseImageFile = new JFileChooser("C:\\Users\\patil\\OneDrive\\Pictures\\Sample Pictures");
        //Filter image extensions
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("IMAGES", "png", "jpg", "jpeg");
        browseImageFile.addChoosableFileFilter(fnef);
        int showOpenDialogue = browseImageFile.showOpenDialog(null);

        if (showOpenDialogue == JFileChooser.APPROVE_OPTION) {
            File selectedImageFile = browseImageFile.getSelectedFile();
            imagePath = selectedImageFile.getAbsolutePath();
            JOptionPane.showMessageDialog(null, imagePath);

            //Display image on jlable
            ImageIcon ii = new ImageIcon(imagePath);
            //Resize image to fit jlabel
            Image image = ii.getImage().getScaledInstance(jLabelImage.getWidth(), jLabelImage.getHeight(), Image.SCALE_SMOOTH);

            jLabelImage.setIcon(new ImageIcon(image));
        }
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        DefaultTableModel model = (DefaultTableModel) tableEmployees.getModel();
        int index=tableEmployees.getSelectedRow();

        String name = tfName.getText();
        String age = tfAge.getText();
        String gender = tfGender.getText();
        String email = tfEmail.getText();
        String phone = tfPhone.getText();
        String empID = tfEmpId.getText();
        String startDate = tfStartDate.getText();
        String level = tfLevel.getText();
        String teamInfo = tfTeamInfo.getText();
        String position = tfPosition.getText();
        String imageIc = imagePath;

        model.setValueAt(name,index,0);
        model.setValueAt(age,index,1);
        model.setValueAt(gender,index,2);
        model.setValueAt(email,index,3);
        model.setValueAt(phone,index,4);
        model.setValueAt(empID,index,5);
        model.setValueAt(startDate,index,6);
        model.setValueAt(level,index,7);
        model.setValueAt(teamInfo,index,8);
        model.setValueAt(position,index,9);
        model.setValueAt(imagePath,tableEmployees.getSelectedRow(),10);

        //Display image on jlable
        ImageIcon ii = new ImageIcon(model.getValueAt(tableEmployees.getSelectedRow(),10).toString());
        //Resize image to fit jlabel
        Image image = ii.getImage().getScaledInstance(jLabelImage.getWidth(), jLabelImage.getHeight(), Image.SCALE_SMOOTH);
        jLabelImage.setIcon(new ImageIcon(image));
        JOptionPane.showMessageDialog(this,"Updated Sucessfully");
//        clearFields();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased

        int compareCombo  = fetchIndex();
       
        DefaultTableModel model = (DefaultTableModel) tableEmployees.getModel();
        String filter = jTextField1.getText().toLowerCase();
        TableRowSorter<DefaultTableModel> newFilter = new TableRowSorter<DefaultTableModel> (model);
        tableEmployees.setRowSorter(newFilter);
        
        if(null==searchFilterate)
         {JOptionPane.showMessageDialog(null, "Please select a column", "Selection Not Available", JOptionPane.ERROR_MESSAGE);}
        
        else switch (searchFilterate) {
                case "Name":
                    newFilter.setRowFilter(RowFilter.regexFilter("(?i)" + filter, compareCombo));
                    break;
                case "Age":
                    newFilter.setRowFilter(RowFilter.regexFilter("(?i)" + filter, compareCombo));
                    break;
                case "Gender":
                    newFilter.setRowFilter(RowFilter.regexFilter("(?i)" + filter, compareCombo));
                    break;
                case "EMail":
                    newFilter.setRowFilter(RowFilter.regexFilter("(?i)" + filter, compareCombo));
                    break;
                case "Phone":
                    newFilter.setRowFilter(RowFilter.regexFilter("(?i)" + filter, compareCombo));
                    break;
                case "Employee ID":
                    newFilter.setRowFilter(RowFilter.regexFilter("(?i)" + filter, compareCombo));
                    break;
                case "Start Date":
                    newFilter.setRowFilter(RowFilter.regexFilter("(?i)" + filter, compareCombo));
                    break;
                case "Level":
                    newFilter.setRowFilter(RowFilter.regexFilter("(?i)" + filter, compareCombo));
                    break;
                case "Team Info":
                    newFilter.setRowFilter(RowFilter.regexFilter("(?i)" + filter, compareCombo));
                    break;
                case "Position Title":
                    newFilter.setRowFilter(RowFilter.regexFilter("(?i)" + filter, compareCombo));
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "Please select a column to filter", "No Selection", JOptionPane.ERROR_MESSAGE);
                    break;
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed

    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void tfTeamInfoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTeamInfoKeyReleased
        String PATTERN="^[a-zA-Z0-9.-]+$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match= patt.matcher(tfTeamInfo.getText());
        String id=tfTeamInfo.getText();
        int length = id.length();

        if(!match.matches()){
            teamInfoLabel.setText("Incorrect");
        }
        else{
            if (length <21) {
                teamInfoLabel.setText(null);
                tfTeamInfo.setEditable(true);

            } else {
                tfTeamInfo.setEditable(false);
                teamInfoLabel.setText("Not so long");
            }
        }
    }//GEN-LAST:event_tfTeamInfoKeyReleased

    private void tfTeamInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTeamInfoActionPerformed
        
    }//GEN-LAST:event_tfTeamInfoActionPerformed

    private void tfEmpIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfEmpIdKeyReleased

        String PATTERN="^[a-zA-Z0-9]+$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match= patt.matcher(tfEmpId.getText());
        String id=tfEmpId.getText();
        int length = id.length();

        if(!match.matches()){
            empIDLbl.setText("Incorrect");
        }
        else{
            if (length <= 10) {
                empIDLbl.setText(null);
                tfEmpId.setEditable(true);

            } else {
                tfEmpId.setEditable(false);
                empIDLbl.setText("ID can be only 10 characters");
            }
        }
    }//GEN-LAST:event_tfEmpIdKeyReleased

    private void tfGenderKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfGenderKeyReleased

    }//GEN-LAST:event_tfGenderKeyReleased

    private void tfGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfGenderActionPerformed

    private void tfAgeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfAgeKeyReleased

        String age=tfAge.getText();
        int length = age.length();
        char c = evt.getKeyChar();
        if(evt.getKeyChar()>='0'&& evt.getKeyChar()<='9'){
            if(length<2){
                tfAge.setEditable(true);
            }else{
                tfAge.setEditable(false);
            }
        }else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE )
            {
                tfAge.setEditable(true);
            }else{
                tfAge.setEditable(false);
                ageLbl.setText("Number only");
            }
        }
    }//GEN-LAST:event_tfAgeKeyReleased

    private void tfAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAgeActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int row = tableEmployees.getSelectedRow();

        if(row<0){
            JOptionPane.showMessageDialog(this,
                "Please select a row to delete",
                "Select row",
                JOptionPane.ERROR_MESSAGE);
        }else{
            DefaultTableModel model = (DefaultTableModel) tableEmployees.getModel();
            model.removeRow(row);
            JOptionPane.showMessageDialog(this,
                "Employee data deleted successfully");
            clearFields();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tfPhoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPhoneKeyPressed
        String phone=tfPhone.getText();
        int length = phone.length();
        char c = evt.getKeyChar();
        if(evt.getKeyChar()>='0'&& evt.getKeyChar()<='9'){
            if(length<10){
                tfPhone.setEditable(true);
            }else{
                tfPhone.setEditable(false);
               
            }
        }else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE )
            {
                tfPhone.setEditable(true);
            }else{
                tfPhone.setEditable(false);
            }
        }
    }//GEN-LAST:event_tfPhoneKeyPressed

    private void tfPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPhoneActionPerformed

    private void tfEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfEmailKeyReleased

        String PATTERN="^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$";
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match= patt.matcher(tfEmail.getText());
        if(!match.matches()){
            emailLbl.setText("Email is incorerct");
        }
        else{
            emailLbl.setText(null);
            tfEmail.setEditable(true);
        }

    }//GEN-LAST:event_tfEmailKeyReleased

    private void tfEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfEmailKeyPressed

    }//GEN-LAST:event_tfEmailKeyPressed

    private void tfNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNameKeyReleased
        char c = evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c)|| Character.isISOControl(c)){
            tfName.setEditable(true);
            nameLBL.setText(null);
        }else{
            tfName.setEditable(false);
            nameLBL.setText("Name must be alphabets only");
        }
    }//GEN-LAST:event_tfNameKeyReleased

    private void tfNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNameKeyPressed

    private void tfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNameActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        tfName.setText("");
        tfAge.setText("");
        tfGender.setText("");
        tfEmail.setText("");
        tfPhone.setText("");
        tfEmpId.setText("");
        tfStartDate.setText("");
        tfLevel.setText("");
        tfTeamInfo.setText("");
        tfPosition.setText("");
        jLabelImage.setIcon(null);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        String name = tfName.getText();
        String age = tfAge.getText();
        String gender = tfGender.getText();
        String email = tfEmail.getText();
        String phone = tfPhone.getText();
        String empID = tfEmpId.getText();
        String startDate = tfStartDate.getText();
        String level = tfLevel.getText();
        String teamInfo = tfTeamInfo.getText();
        String position = tfPosition.getText();
        String image = imagePath;
        String selectedImagePath = "";

        if(name.isEmpty() || age.isEmpty()||gender.isEmpty()||email.isEmpty()|| phone.isEmpty()||empID.isEmpty()||startDate.isEmpty()||level.isEmpty()||teamInfo.isEmpty() || position.isEmpty()||image==null){
            JOptionPane.showMessageDialog(this,
                "Please enter all the fields",
                "Try Again",
                JOptionPane.ERROR_MESSAGE);
        }
        else{

            DefaultTableModel model = (DefaultTableModel) tableEmployees.getModel();

            model.addRow(new Object[] {name,age,gender, email, phone, empID, startDate, level, teamInfo, position, imagePath});

            JOptionPane.showMessageDialog(null, "Data Inserted");
            clearFields();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void tfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailActionPerformed

    private void tfGenderKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfGenderKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfGenderKeyPressed

    private void tfStartDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfStartDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStartDateActionPerformed

    private void tfStartDateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfStartDateKeyReleased
//        String PATTERN="^[1-12]+[-]{1}+[1-31]+[-]{1}+[2020-2022]+$";
//        Pattern patt = Pattern.compile(PATTERN);
//        Matcher match= patt.matcher(tfStartDate.getText());
//        if(!match.matches()){
//            dateLbl.setText("M-D-Y");
//        }
//        else{
//            dateLbl.setText(null);
//            tfStartDate.setEditable(true);
//        }
    }//GEN-LAST:event_tfStartDateKeyReleased

    private void tfPositionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPositionKeyReleased
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c)||Character.isWhitespace(c)|| Character.isISOControl(c)){
            tfPosition.setEditable(true);
             positionLbl.setText(null);
        }else{
            tfPosition.setEditable(false);
             positionLbl.setText("Alphabets only");
        }
    }//GEN-LAST:event_tfPositionKeyReleased

    private void itemBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBoxActionPerformed
       searchFilterate = itemBox.getSelectedItem().toString();
    }//GEN-LAST:event_itemBoxActionPerformed

    private void itemBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemBoxKeyReleased
        
    }//GEN-LAST:event_itemBoxKeyReleased

    private void itemBoxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemBoxMouseExited
       searchFilterate = itemBox.getSelectedItem().toString();
    }//GEN-LAST:event_itemBoxMouseExited
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
            
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmployee().setVisible(true);
            }
        });
    }
    private String imagePath;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agLabel;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JLabel ageLbl;
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JLabel empIDLabel;
    private javax.swing.JLabel empIDLbl;
    private javax.swing.ButtonGroup genderGroup;
    private javax.swing.JComboBox<String> itemBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    public static javax.swing.JLabel jLabelImage;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JLabel nameLBL;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel positionLbl;
    private javax.swing.JButton reviewButton;
    private javax.swing.JTable tableEmployees;
    private javax.swing.JLabel teamInfoLabel;
    private javax.swing.JLabel teamLabel;
    public static javax.swing.JTextField tfAge;
    public static javax.swing.JTextField tfEmail;
    public static javax.swing.JTextField tfEmpId;
    public static javax.swing.JTextField tfGender;
    public static javax.swing.JTextField tfLevel;
    public static javax.swing.JTextField tfName;
    public static javax.swing.JTextField tfPhone;
    public static javax.swing.JTextField tfPosition;
    public static javax.swing.JTextField tfStartDate;
    public static javax.swing.JTextField tfTeamInfo;
    // End of variables declaration//GEN-END:variables

    private JFileChooser JFileChooser(String cUserspatilOneDrivePicturesSample_Picture) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void clearFields() {
        try{
            tfName.setText("");
            tfAge.setText("");
            tfGender.setText("");
            tfEmail.setText("");
            tfPhone.setText("");
            tfEmpId.setText("");
            tfStartDate.setText("");
            tfLevel.setText("");
            tfTeamInfo.setText("");
            tfPosition.setText("");
            jLabelImage.setIcon(null);
        } catch(Exception e){
            throw new UnsupportedOperationException("Not supported yet.");
        }
        
    }

    private static class pattern {

        private static Matcher matcher(String text) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public pattern() {
        }
    }

    private static class Second {

        public Second(DefaultTableModel model) {
        }

        private void setVisible(boolean b) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }
    }
}
